"""stat

Revision ID: 07fb144f3d2b
Revises: 1cb51a032086
Create Date: 2024-12-18 22:43:28.900486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fb144f3d2b'
down_revision: Union[str, None] = '1cb51a032086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_phone_num', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_phone_num'], ['public.users.phone_number'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics', schema='public')
    # ### end Alembic commands ###
