"""delete foreignkey

Revision ID: 40ef28f83cbc
Revises: 07fb144f3d2b
Create Date: 2024-12-18 22:55:18.189651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ef28f83cbc'
down_revision: Union[str, None] = '07fb144f3d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statistics_user_phone_num_fkey', 'statistics', type_='foreignkey')
    op.drop_column('statistics', 'user_phone_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('user_phone_num', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('statistics_user_phone_num_fkey', 'statistics', 'users', ['user_phone_num'], ['phone_number'])
    # ### end Alembic commands ###
